# Generated by Django 4.2.7 on 2023-12-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanche', models.CharField(max_length=100, verbose_name='Dog')),
                ('descricao', models.TextField(verbose_name='Descriçao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Lanche',
                'verbose_name_plural': 'Lanches',
            },
        ),
    ]
